### ISSUE TITLE
[Bug Report] HTML wont render on renderBodyCell

### ISSUE THREAD

**Issue by gokigoks** [Happy-Coding-Clans/vue-easytable#360]
### I am opening an issue for
vue-easytable

### Issue Type
Bug

###  Issue Title
HTML wont render on renderBodyCell

### library Version
2.4.0

### Vue Type
2.2.6

### Browser Type
Chrome 88.0.4324.96

### System version
Linux

### Reproduction url
<a href="https://codepen.io/gokigoks/pen/WNoZmYw" target="_blank">https://codepen.io/gokigoks/pen/WNoZmYw</a>

### Step to reproduce
HTML not being rendered in renderBodyCell and displays as text.

### What is expected?
This should have rendered the text and displayed the HTML 

### What is actually happening?
shows as text only

**Comment by gokigoks** [comment]
The samples on the docs don't work when in a JS file, at least for the render functions. Is there a way I could add/render HTML in a cell?

**Comment by huangshuwei** [comment]
It looks like a bug of codepen. I'll look into it further

**Comment by huangshuwei** [comment]
1、The new version（2.x） is no longer supported rendering strings to html in the cell header/body/footer.
2、The new version（2.x） uses JSX instead of v-html, It can effectively prevent [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting)
3、I've changed the online example to the CodeSandBox in [official document](http://doc.huangsw.com/vue-easytable/#/en/doc/intro). codepen or jsfiddle are not recommended. They are not friendly to JSX support.
