### ISSUE TITLE
[Bug Report] sort and filter problem

### ISSUE THREAD

**Issue by oliolivia** [Happy-Coding-Clans/vue-easytable#422]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
sort and filter problem

### 仓库版本
2.11.0

### Vue 版本
2.6.14

### 浏览器
firefox 93.0beta

### 系统类型
macOS

### 重现链接
<a href="https://codesandbox.io/s/zealous-burnell-zshcx?file=/Example.vue" target="_blank">https://codesandbox.io/s/zealous-burnell-zshcx?file=/Example.vue</a>

### 重现步骤
move "columns" from "computed" to "data"

### 期望的结果是什么？
find a way to make both filter(dynamically) and sort work

### 实际的结果是什么？
1. to filter by a dynamic filterList, we need to put the definition of columns in computed ---> in this case, the sort doesn't work
2. to make the sort work, we need to put the definition of columns in data ---> in this case, the filterList can not be calculated or fetched by a request

**Comment by huangshuwei** [comment]
Sorry for the late reply. 
In your case, the `sortBy` of age column is reset because the `columns` are recalculated in computed , resulting in the failure of sorting effect.

Here are 2 solutions you can try.
Solution 1: 
Add a `ageSortBy` property in data. When clicking the sorting icon triggers a sorting change event, the current sorting status is recorded to avoid sorting failure caused by column recalculation. Here is an example: https://codesandbox.io/s/dreamy-chatelet-8n58b?file=/Example.vue

Solution 2:
You can put the definition of columns in data, **The filterList can be calculated or fetched by a request**, You can set filterList directly, Such as:
```javascript
this.columns = this.columns.map((column, index) => {
        // age column
        if (index === 0) {
            column.filter.filterList = this.tableData.map((x) => {
                return { value: x.name, label: x.name, selected: false };
            });
        }

        return column;
    });
```
Here is an example:https://codesandbox.io/s/dreamy-chatelet-8n58b?file=/Example.vue](https://codesandbox.io/s/vue-easytable-2-11-0-example-forked-si2gz?file=/Example.vue)
